# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: network.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\x12\x08jokinojo\"\x86\x03\n\x0bRequestData\x12\x30\n\x08\x64\x61taType\x18\x01 \x01(\x0e\x32\x1e.jokinojo.RequestData.DataType\x12\x15\n\x08username\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06roomId\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12\x19\n\x0ctimePosition\x18\x04 \x01(\x05H\x02\x88\x01\x01\x12\x14\n\x07resumed\x18\x05 \x01(\x08H\x03\x88\x01\x01\x12\x16\n\tvideoName\x18\x06 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0b\x63hatMessage\x18\x07 \x01(\tH\x05\x88\x01\x01\"c\n\x08\x44\x61taType\x12\x0f\n\x0b\x43REATE_ROOM\x10\x00\x12\r\n\tJOIN_ROOM\x10\x01\x12\x08\n\x04QUIT\x10\x02\x12\x08\n\x04SYNC\x10\x03\x12\x0e\n\nVIDEO_NAME\x10\x04\x12\t\n\x05READY\x10\x05\x12\x08\n\x04\x43HAT\x10\x06\x42\x0b\n\t_usernameB\t\n\x07_roomIdB\x0f\n\r_timePositionB\n\n\x08_resumedB\x0c\n\n_videoNameB\x0e\n\x0c_chatMessage\"\xa0\x03\n\x0cResponseData\x12\x31\n\x08\x64\x61taType\x18\x01 \x01(\x0e\x32\x1f.jokinojo.ResponseData.DataType\x12\x13\n\x06roomId\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\tusernames\x18\x03 \x03(\t\x12\x15\n\x08username\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x19\n\x0ctimePosition\x18\x05 \x01(\x05H\x02\x88\x01\x01\x12\x14\n\x07resumed\x18\x06 \x01(\x08H\x03\x88\x01\x01\x12\x16\n\tvideoName\x18\x07 \x01(\tH\x04\x88\x01\x01\x12\x18\n\x0b\x63hatMessage\x18\x08 \x01(\tH\x05\x88\x01\x01\"h\n\x08\x44\x61taType\x12\x0f\n\x0b\x43REATE_ROOM\x10\x00\x12\r\n\tJOIN_ROOM\x10\x01\x12\r\n\tUSER_LEFT\x10\x02\x12\x08\n\x04SYNC\x10\x03\x12\x0e\n\nVIDEO_NAME\x10\x04\x12\t\n\x05READY\x10\x05\x12\x08\n\x04\x43HAT\x10\x06\x42\t\n\x07_roomIdB\x0b\n\t_usernameB\x0f\n\r_timePositionB\n\n\x08_resumedB\x0c\n\n_videoNameB\x0e\n\x0c_chatMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTDATA']._serialized_start=28
  _globals['_REQUESTDATA']._serialized_end=418
  _globals['_REQUESTDATA_DATATYPE']._serialized_start=236
  _globals['_REQUESTDATA_DATATYPE']._serialized_end=335
  _globals['_RESPONSEDATA']._serialized_start=421
  _globals['_RESPONSEDATA']._serialized_end=837
  _globals['_RESPONSEDATA_DATATYPE']._serialized_start=650
  _globals['_RESPONSEDATA_DATATYPE']._serialized_end=754
# @@protoc_insertion_point(module_scope)
