# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\x12\x08jokinojo\"\x95\x02\n\x0bRequestData\x12\x30\n\x08\x64\x61taType\x18\x01 \x01(\x0e\x32\x1e.jokinojo.RequestData.DataType\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06roomId\x18\x03 \x01(\x05\x12\x14\n\x0ctimePosition\x18\x04 \x01(\x05\x12\x0f\n\x07resumed\x18\x05 \x01(\x08\x12\x11\n\tvideoName\x18\x06 \x01(\t\x12\x13\n\x0b\x63hatMessage\x18\x07 \x01(\t\"c\n\x08\x44\x61taType\x12\x0f\n\x0b\x43REATE_ROOM\x10\x00\x12\r\n\tJOIN_ROOM\x10\x01\x12\x08\n\x04QUIT\x10\x02\x12\x08\n\x04SYNC\x10\x03\x12\x0e\n\nVIDEO_NAME\x10\x04\x12\t\n\x05READY\x10\x05\x12\x08\n\x04\x43HAT\x10\x06\"\xaf\x02\n\x0cResponseData\x12\x31\n\x08\x64\x61taType\x18\x01 \x01(\x0e\x32\x1f.jokinojo.ResponseData.DataType\x12\x0e\n\x06roomId\x18\x02 \x01(\x05\x12\x11\n\tusernames\x18\x03 \x03(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x14\n\x0ctimePosition\x18\x05 \x01(\x05\x12\x0f\n\x07resumed\x18\x06 \x01(\x08\x12\x11\n\tvideoName\x18\x07 \x01(\t\x12\x13\n\x0b\x63hatMessage\x18\x08 \x01(\t\"h\n\x08\x44\x61taType\x12\x0f\n\x0b\x43REATE_ROOM\x10\x00\x12\r\n\tJOIN_ROOM\x10\x01\x12\r\n\tUSER_LEFT\x10\x02\x12\x08\n\x04SYNC\x10\x03\x12\x0e\n\nVIDEO_NAME\x10\x04\x12\t\n\x05READY\x10\x05\x12\x08\n\x04\x43HAT\x10\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTDATA._serialized_start=28
  _REQUESTDATA._serialized_end=305
  _REQUESTDATA_DATATYPE._serialized_start=206
  _REQUESTDATA_DATATYPE._serialized_end=305
  _RESPONSEDATA._serialized_start=308
  _RESPONSEDATA._serialized_end=611
  _RESPONSEDATA_DATATYPE._serialized_start=507
  _RESPONSEDATA_DATATYPE._serialized_end=611
# @@protoc_insertion_point(module_scope)
